export { accounts, authSchema, sessions, users, verifications } from "./auth"
export {
  jobRuns,
  userSettings,
  type JobRunInsert,
  type JobRunSelect,
  type JobRunStatus,
  type UserSettingsInsert,
} from "./app"
export {
  documentAttachments,
  emailSyncCursors,
  oauthConnections,
  rawDocuments,
  type DocumentAttachmentInsert,
  type DocumentAttachmentParseStatus,
  type DocumentAttachmentSelect,
  type EmailSyncCursorSelect,
  type OauthConnectionInsert,
  type OauthConnectionSelect,
  type OauthConnectionStatus,
  type RawDocumentInsert,
  type RawDocumentRelevanceLabel,
  type RawDocumentRelevanceStage,
  type RawDocumentSelect,
  type RawDocumentSourceType,
} from "./ingestion"
export {
  extractedSignals,
  modelRuns,
  type ExtractedSignalCandidateEventType,
  type ExtractedSignalInsert,
  type ExtractedSignalSelect,
  type ExtractedSignalStatus,
  type ExtractedSignalType,
  type ModelRunInsert,
  type ModelRunSelect,
  type ModelRunStatus,
  type ModelRunTaskType,
} from "./extraction"
export {
  financialEventValuations,
  fxRatesDaily,
  type FinancialEventValuationInsert,
  type FinancialEventValuationKind,
  type FinancialEventValuationSelect,
  type FxRateDailyInsert,
  type FxRateDailySelect,
  type FxRateProvider,
} from "./fx"
export {
  financialInstitutionAliases,
  financialInstitutions,
  paymentInstrumentObservations,
  type FinancialInstitutionAliasInsert,
  type FinancialInstitutionAliasSelect,
  type FinancialInstitutionInsert,
  type FinancialInstitutionSelect,
  type ObservationResolutionStatus,
  type ObservationSourceKind,
  type PaymentInstrumentObservationInsert,
  type PaymentInstrumentObservationSelect,
} from "./instrument-resolution"
export {
  merchantObservations,
  paymentProcessorAliases,
  paymentProcessors,
  type MerchantObservationInsert,
  type MerchantObservationSelect,
  type MerchantObservationSourceKind,
  type PaymentProcessorAliasInsert,
  type PaymentProcessorAliasSelect,
  type PaymentProcessorInsert,
  type PaymentProcessorSelect,
  type PaymentProcessorAliasResolutionStatus,
} from "./merchant-resolution"
export {
  categories,
  financialEvents,
  financialEventSources,
  merchantAliases,
  merchants,
  paymentInstruments,
  reviewQueueItems,
  type CategoryInsert,
  type CategoryKind,
  type CategorySelect,
  type FinancialEventDirection,
  type FinancialEventInsert,
  type FinancialEventSelect,
  type FinancialEventSourceInsert,
  type FinancialEventSourceSelect,
  type FinancialEventStatus,
  type FinancialEventType,
  type MerchantAliasInsert,
  type MerchantAliasSelect,
  type MerchantInsert,
  type MerchantSelect,
  type MerchantType,
  type PaymentInstrumentInsert,
  type PaymentInstrumentSelect,
  type PaymentInstrumentStatus,
  type PaymentInstrumentType,
  type ReviewQueueItemInsert,
  type ReviewQueueItemSelect,
  type ReviewQueueItemStatus,
  type ReviewQueueItemType,
} from "./ledger"
export {
  emiPlans,
  incomeStreams,
  recurringObligations,
  type EmiPlanInsert,
  type EmiPlanSelect,
  type EmiPlanStatus,
  type IncomeStreamInsert,
  type IncomeStreamSelect,
  type IncomeStreamStatus,
  type IncomeStreamType,
  type RecurringCadence,
  type RecurringObligationInsert,
  type RecurringObligationSelect,
  type RecurringObligationStatus,
  type RecurringObligationType,
} from "./recurring"

import { authSchema } from "./auth"
import { jobRuns, userSettings } from "./app"
import { extractedSignals, modelRuns } from "./extraction"
import { financialEventValuations, fxRatesDaily } from "./fx"
import {
  financialInstitutionAliases,
  financialInstitutions,
  paymentInstrumentObservations,
} from "./instrument-resolution"
import {
  merchantObservations,
  paymentProcessorAliases,
  paymentProcessors,
} from "./merchant-resolution"
import {
  categories,
  financialEvents,
  financialEventSources,
  merchantAliases,
  merchants,
  paymentInstruments,
  reviewQueueItems,
} from "./ledger"
import { emiPlans, incomeStreams, recurringObligations } from "./recurring"
import {
  documentAttachments,
  emailSyncCursors,
  oauthConnections,
  rawDocuments,
} from "./ingestion"

export const schema = {
  ...authSchema,
  userSettings,
  jobRuns,
  oauthConnections,
  emailSyncCursors,
  rawDocuments,
  documentAttachments,
  modelRuns,
  extractedSignals,
  fxRatesDaily,
  financialEventValuations,
  financialInstitutions,
  financialInstitutionAliases,
  paymentInstrumentObservations,
  paymentProcessors,
  paymentProcessorAliases,
  merchantObservations,
  merchants,
  merchantAliases,
  paymentInstruments,
  categories,
  financialEvents,
  financialEventSources,
  reviewQueueItems,
  recurringObligations,
  emiPlans,
  incomeStreams,
}
