export { accounts, authSchema, sessions, users, verifications } from "./auth"
export {
  adviceRefreshStates,
  adviceItems,
  financialGoals,
  goalContributionSnapshots,
  type AdviceRefreshStateInsert,
  type AdviceRefreshStateSelect,
  type AdviceItemAction,
  type AdviceItemActionType,
  type AdviceItemInsert,
  type AdviceItemPriority,
  type AdviceItemSelect,
  type AdviceItemStatus,
  type AdviceItemTriggerType,
  type FinancialGoalInsert,
  type FinancialGoalSelect,
  type FinancialGoalStatus,
  type FinancialGoalType,
  type GoalContributionSnapshotInsert,
  type GoalContributionSnapshotSelect,
} from "./advice"
export {
  memoryFacts,
  type MemoryFactInsert,
  type MemoryFactSelect,
  type MemoryFactSource,
  type MemoryFactSubjectType,
  type MemoryFactType,
} from "./memory"
export {
  feedbackEvents,
  type FeedbackEventInsert,
  type FeedbackEventSelect,
  type FeedbackEventSourceSurface,
  type FeedbackEventTargetType,
} from "./feedback"
export {
  balanceAnchors,
  balanceObservations,
  forecastRuns,
  forecastSnapshots,
  type BalanceAnchorInsert,
  type BalanceAnchorSelect,
  type BalanceObservationInsert,
  type BalanceObservationSelect,
  type BalanceObservationKind,
  type BalanceObservationSource,
  type BalanceObservationStatus,
  type ForecastRunInsert,
  type ForecastRunSelect,
  type ForecastRunStatus,
  type ForecastRunType,
  type ForecastSnapshotInsert,
  type ForecastSnapshotSelect,
} from "./forecast"
export {
  jobRuns,
  userSettings,
  type JobRunInsert,
  type JobRunSelect,
  type JobRunStatus,
  type UserSettingsInsert,
} from "./app"
export {
  documentAttachments,
  emailSyncCursors,
  gmailMessageRelevanceCaches,
  oauthConnections,
  rawDocuments,
  type DocumentAttachmentInsert,
  type DocumentAttachmentParseStatus,
  type DocumentAttachmentSelect,
  type EmailSyncCursorSelect,
  type GmailMessageRelevanceCacheInsert,
  type GmailMessageRelevanceCacheSelect,
  type OauthConnectionInsert,
  type OauthConnectionSelect,
  type OauthConnectionStatus,
  type RawDocumentInsert,
  type RawDocumentRelevanceLabel,
  type RawDocumentRelevanceStage,
  type RawDocumentSelect,
  type RawDocumentSourceType,
} from "./ingestion"
export {
  extractedSignals,
  modelRuns,
  type ExtractedSignalCandidateEventType,
  type ExtractedSignalAccountRelationshipHint,
  type ExtractedSignalBalanceEvidenceStrength,
  type ExtractedSignalInsert,
  type ExtractedSignalSelect,
  type ExtractedSignalStatus,
  type ExtractedSignalType,
  type ModelRunInsert,
  type ModelRunSelect,
  type ModelRunStatus,
  type ModelRunTaskType,
} from "./extraction"
export {
  financialEventValuations,
  fxRatesDaily,
  type FinancialEventValuationInsert,
  type FinancialEventValuationKind,
  type FinancialEventValuationSelect,
  type FxRateDailyInsert,
  type FxRateDailySelect,
  type FxRateProvider,
} from "./fx"
export {
  financialInstitutionAliases,
  financialInstitutions,
  paymentInstrumentObservations,
  type FinancialInstitutionAliasInsert,
  type FinancialInstitutionAliasSelect,
  type FinancialInstitutionInsert,
  type FinancialInstitutionSelect,
  type ObservationResolutionStatus,
  type ObservationSourceKind,
  type PaymentInstrumentObservationInsert,
  type PaymentInstrumentObservationSelect,
} from "./instrument-resolution"
export {
  merchantObservations,
  paymentProcessorAliases,
  paymentProcessors,
  type MerchantObservationInsert,
  type MerchantObservationSelect,
  type MerchantObservationSourceKind,
  type PaymentProcessorAliasInsert,
  type PaymentProcessorAliasSelect,
  type PaymentProcessorInsert,
  type PaymentProcessorSelect,
  type PaymentProcessorAliasResolutionStatus,
} from "./merchant-resolution"
export {
  categories,
  financialEvents,
  financialEventSources,
  merchantAliases,
  merchants,
  paymentInstruments,
  reviewQueueItems,
  type CategoryInsert,
  type CategoryKind,
  type CategorySelect,
  type FinancialEventDirection,
  type FinancialEventInsert,
  type FinancialEventSelect,
  type FinancialEventSourceInsert,
  type FinancialEventSourceSelect,
  type FinancialEventStatus,
  type FinancialEventType,
  type MerchantAliasInsert,
  type MerchantAliasSelect,
  type MerchantInsert,
  type MerchantSelect,
  type MerchantType,
  type PaymentInstrumentInsert,
  type PaymentInstrumentSelect,
  type PaymentInstrumentStatus,
  type PaymentInstrumentType,
  type ReviewQueueItemInsert,
  type ReviewQueueItemSelect,
  type ReviewQueueItemStatus,
  type ReviewQueueItemType,
} from "./ledger"
export {
  emiPlans,
  incomeStreams,
  recurringObligations,
  type EmiPlanInsert,
  type EmiPlanSelect,
  type EmiPlanStatus,
  type IncomeStreamInsert,
  type IncomeStreamSelect,
  type IncomeStreamStatus,
  type IncomeStreamType,
  type RecurringCadence,
  type RecurringObligationInsert,
  type RecurringObligationSelect,
  type RecurringObligationStatus,
  type RecurringObligationType,
} from "./recurring"

import {
  adviceRefreshStates,
  adviceItems,
  financialGoals,
  goalContributionSnapshots,
} from "./advice"
import { authSchema } from "./auth"
import { jobRuns, userSettings } from "./app"
import { feedbackEvents } from "./feedback"
import { memoryFacts } from "./memory"
import { extractedSignals, modelRuns } from "./extraction"
import {
  balanceAnchors,
  balanceObservations,
  forecastRuns,
  forecastSnapshots,
} from "./forecast"
import { financialEventValuations, fxRatesDaily } from "./fx"
import {
  financialInstitutionAliases,
  financialInstitutions,
  paymentInstrumentObservations,
} from "./instrument-resolution"
import {
  merchantObservations,
  paymentProcessorAliases,
  paymentProcessors,
} from "./merchant-resolution"
import {
  categories,
  financialEvents,
  financialEventSources,
  merchantAliases,
  merchants,
  paymentInstruments,
  reviewQueueItems,
} from "./ledger"
import { emiPlans, incomeStreams, recurringObligations } from "./recurring"
import {
  documentAttachments,
  emailSyncCursors,
  gmailMessageRelevanceCaches,
  oauthConnections,
  rawDocuments,
} from "./ingestion"

export const schema = {
  ...authSchema,
  adviceItems,
  adviceRefreshStates,
  financialGoals,
  goalContributionSnapshots,
  userSettings,
  jobRuns,
  memoryFacts,
  feedbackEvents,
  oauthConnections,
  emailSyncCursors,
  gmailMessageRelevanceCaches,
  rawDocuments,
  documentAttachments,
  modelRuns,
  extractedSignals,
  forecastRuns,
  forecastSnapshots,
  balanceObservations,
  balanceAnchors,
  fxRatesDaily,
  financialEventValuations,
  financialInstitutions,
  financialInstitutionAliases,
  paymentInstrumentObservations,
  paymentProcessors,
  paymentProcessorAliases,
  merchantObservations,
  merchants,
  merchantAliases,
  paymentInstruments,
  categories,
  financialEvents,
  financialEventSources,
  reviewQueueItems,
  recurringObligations,
  emiPlans,
  incomeStreams,
}
