export { accounts, authSchema, sessions, users, verifications } from "./auth"
export {
  jobRuns,
  userSettings,
  type JobRunInsert,
  type JobRunSelect,
  type JobRunStatus,
  type UserSettingsInsert,
} from "./app"
export {
  documentAttachments,
  emailSyncCursors,
  oauthConnections,
  rawDocuments,
  type DocumentAttachmentInsert,
  type DocumentAttachmentParseStatus,
  type DocumentAttachmentSelect,
  type EmailSyncCursorSelect,
  type OauthConnectionInsert,
  type OauthConnectionSelect,
  type OauthConnectionStatus,
  type RawDocumentInsert,
  type RawDocumentRelevanceLabel,
  type RawDocumentRelevanceStage,
  type RawDocumentSelect,
  type RawDocumentSourceType,
} from "./ingestion"
export {
  extractedSignals,
  modelRuns,
  type ExtractedSignalCandidateEventType,
  type ExtractedSignalInsert,
  type ExtractedSignalSelect,
  type ExtractedSignalStatus,
  type ExtractedSignalType,
  type ModelRunInsert,
  type ModelRunSelect,
  type ModelRunStatus,
  type ModelRunTaskType,
} from "./extraction"
export {
  categories,
  financialEvents,
  financialEventSources,
  merchantAliases,
  merchants,
  paymentInstruments,
  reviewQueueItems,
  type CategoryInsert,
  type CategoryKind,
  type CategorySelect,
  type FinancialEventDirection,
  type FinancialEventInsert,
  type FinancialEventSelect,
  type FinancialEventSourceInsert,
  type FinancialEventSourceSelect,
  type FinancialEventStatus,
  type FinancialEventType,
  type MerchantAliasInsert,
  type MerchantAliasSelect,
  type MerchantInsert,
  type MerchantSelect,
  type MerchantType,
  type PaymentInstrumentInsert,
  type PaymentInstrumentSelect,
  type PaymentInstrumentStatus,
  type PaymentInstrumentType,
  type ReviewQueueItemInsert,
  type ReviewQueueItemSelect,
  type ReviewQueueItemStatus,
  type ReviewQueueItemType,
} from "./ledger"

import { authSchema } from "./auth"
import { jobRuns, userSettings } from "./app"
import { extractedSignals, modelRuns } from "./extraction"
import {
  categories,
  financialEvents,
  financialEventSources,
  merchantAliases,
  merchants,
  paymentInstruments,
  reviewQueueItems,
} from "./ledger"
import {
  documentAttachments,
  emailSyncCursors,
  oauthConnections,
  rawDocuments,
} from "./ingestion"

export const schema = {
  ...authSchema,
  userSettings,
  jobRuns,
  oauthConnections,
  emailSyncCursors,
  rawDocuments,
  documentAttachments,
  modelRuns,
  extractedSignals,
  merchants,
  merchantAliases,
  paymentInstruments,
  categories,
  financialEvents,
  financialEventSources,
  reviewQueueItems,
}
